# Generated by Django 4.1 on 2022-08-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_devices_devicestype_delete_laptop_delete_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devices",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos/files_photo"
            ),
        ),
    ]
