# Generated by Django 4.1 on 2022-08-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_alter_devices_options_alter_devicestype_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devices",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="media/images"),
        ),
    ]
