# Generated by Django 4.1 on 2022-08-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_alter_devices_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devices",
            name="img",
        ),
        migrations.AddField(
            model_name="devices",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
