# Generated by Django 4.1 on 2022-08-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0006_remove_devices_img_devices_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devices",
            name="image",
            field=models.ImageField(
                blank=True,
                height_field=300,
                null=True,
                upload_to="images/",
                width_field=300,
            ),
        ),
    ]
