# Generated by Django 4.1 on 2022-08-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0007_alter_devices_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devices",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
